### ISSUE TITLE
Rename and extend or merge and remove the repository

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/sliceutil#15]
We also have a repository called [utils](https://github.com/projectdiscovery/utils) that contains a `sliceutil` and `mapsutil`.
We should either rename this repository into `collectionutil` and move the code slice and maputil here from the general `utils` repository, or move the code from this repository to the `utils` repository and remove this project.

**Comment by Mzack9999** [comment]
Todo list:
- [x] Complete ongoing developments
- [x] Final release
- [x] Archive the repository (read only) => Developments will continue at https://github.com/projectdiscovery/utils
